// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiEtBJM_wIgQDJXWcxEzLQf0P5B_SsAuo',
    appId: '1:693056223599:android:1ac70529cf24bce27c509a',
    messagingSenderId: '693056223599',
    projectId: 'travellapp-e4c9f',
    storageBucket: 'travellapp-e4c9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3Oq8ocTU4NLD3QmMJHnubv9pquz6xTZE',
    appId: '1:693056223599:ios:e040d44dd23792177c509a',
    messagingSenderId: '693056223599',
    projectId: 'travellapp-e4c9f',
    storageBucket: 'travellapp-e4c9f.appspot.com',
    iosBundleId: 'com.example.travellapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3Oq8ocTU4NLD3QmMJHnubv9pquz6xTZE',
    appId: '1:693056223599:ios:e040d44dd23792177c509a',
    messagingSenderId: '693056223599',
    projectId: 'travellapp-e4c9f',
    storageBucket: 'travellapp-e4c9f.appspot.com',
    iosBundleId: 'com.example.travellapp',
  );

}